### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by tglander** [sanic-org/sanic-ext#204]
# Usecase
I would like to document a query parameter that is given as a JSON structure in order to define complex filter options (e.g. attribute + filter operation in, not-in, eq, lt, gt,...). According to openapi documentation, this should be possible using content specs instead of schema  https://swagger.io/docs/specification/describing-parameters/#schema-vs-content

an example for a filter parameter with a nested object
```
        - in: query
          name: filter
          content:
            application/json:
              schema:
                type: object
                properties:
                  captureId:
                    type: object
                    properties:
                      IN:
                        type: array
                        items:
                          type: string
                      NOTIN:
                        type: array
                        items:
                          type: string
```

**Describe the solution you'd like**
As a solution, I think that the Parameter constructor function should also allow to provide the option to provide the `content` object. Looking at the current code, it might work to accept the `MediaType`, which is currently only used to construct body and response components.

Workarounds I tried:

1. I tried to work around this using kwargs of `Parameter` constructor or other options using a dict, but at some point the SpecificationBuilder requires presence of schema and forces it to be string, so in the end it does not work
2. I also tried to simplify the nested object and use deepObject style, but this does not work because sanic-ext cannot understand it. E.g. parameters given like `?captureId[IN]=1,2,3&captureId[NOTIN]=5` are not merged together into an object like `captureId={IN:[1,2,3], NOTIN=[5]}`
3.
